#!/usr/bin/env node
// Builds the offline gazetteer + airports the browser needs, into public/data
// as compact JSON. Large + third-party, so gitignored — regenerated by the
// build (`pnpm prep:data`). Served as static assets; fetched in a Web Worker
// only after the user drops their file, so raw data never leaves the browser.
//
//   cities   → GeoNames cities15000 (CC-BY 4.0)
//   airports → OurAirports large/medium airports (public domain)

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const dataDir = join(root, 'public', 'data');
const tmpDir = join(root, '.tmp-data');

const GEONAMES = 'https://download.geonames.org/export/dump';
const OURAIRPORTS = 'https://davidmegginson.github.io/ourairports-data/airports.csv';

const round = (n) => Math.round(n * 10000) / 10000;

function download(url, dest) {
	console.log(`↓ ${url}`);
	execSync(`curl -fsSL --max-time 120 -o ${JSON.stringify(dest)} ${JSON.stringify(url)}`, {
		stdio: ['ignore', 'ignore', 'inherit'],
	});
}

function parseCsvLine(line) {
	const out = [];
	let field = '';
	let q = false;
	for (let i = 0; i < line.length; i++) {
		const c = line[i];
		if (q) {
			if (c === '"') {
				if (line[i + 1] === '"') {
					field += '"';
					i++;
				} else q = false;
			} else field += c;
		} else if (c === '"') q = true;
		else if (c === ',') {
			out.push(field);
			field = '';
		} else field += c;
	}
	out.push(field);
	return out;
}

function buildCities() {
	const countries = new Map();
	for (const line of readFileSync(join(tmpDir, 'countryInfo.txt'), 'utf8').split('\n')) {
		if (!line || line.startsWith('#')) continue;
		const c = line.split('\t');
		if (c[0] && c[4]) countries.set(c[0], c[4]);
	}
	const admin1 = new Map();
	for (const line of readFileSync(join(tmpDir, 'admin1CodesASCII.txt'), 'utf8').split('\n')) {
		if (!line) continue;
		const c = line.split('\t');
		if (c[0] && c[1]) admin1.set(c[0], c[1]);
	}
	const cities = [];
	for (const line of readFileSync(join(tmpDir, 'cities15000.txt'), 'utf8').split('\n')) {
		if (!line) continue;
		const c = line.split('\t');
		const name = c[1];
		const lat = Number.parseFloat(c[4]);
		const lng = Number.parseFloat(c[5]);
		const countryCode = c[8];
		const region = admin1.get(`${countryCode}.${c[10]}`);
		const population = Number.parseInt(c[14], 10) || 0;
		if (!name || !countryCode || !Number.isFinite(lat) || !Number.isFinite(lng)) continue;
		cities.push({
			name,
			...(region ? { region } : {}),
			country: countries.get(countryCode) ?? countryCode,
			countryCode,
			lat: round(lat),
			lng: round(lng),
			population,
		});
	}
	return cities;
}

function buildAirports() {
	const rows = readFileSync(join(tmpDir, 'airports.csv'), 'utf8').split('\n');
	const header = parseCsvLine(rows[0]);
	const iType = header.indexOf('type');
	const iLat = header.indexOf('latitude_deg');
	const iLng = header.indexOf('longitude_deg');
	const airports = [];
	for (let i = 1; i < rows.length; i++) {
		if (!rows[i]) continue;
		const cols = parseCsvLine(rows[i]);
		if (cols[iType] !== 'large_airport' && cols[iType] !== 'medium_airport') continue;
		const lat = Number.parseFloat(cols[iLat]);
		const lng = Number.parseFloat(cols[iLng]);
		if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;
		airports.push({ lat: round(lat), lng: round(lng) });
	}
	return airports;
}

function main() {
	rmSync(tmpDir, { recursive: true, force: true });
	mkdirSync(tmpDir, { recursive: true });
	if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });

	download(`${GEONAMES}/cities15000.zip`, join(tmpDir, 'cities15000.zip'));
	download(`${GEONAMES}/admin1CodesASCII.txt`, join(tmpDir, 'admin1CodesASCII.txt'));
	download(`${GEONAMES}/countryInfo.txt`, join(tmpDir, 'countryInfo.txt'));
	download(OURAIRPORTS, join(tmpDir, 'airports.csv'));
	execSync(`unzip -o -q ${JSON.stringify(join(tmpDir, 'cities15000.zip'))} -d ${JSON.stringify(tmpDir)}`);

	const cities = buildCities();
	const airports = buildAirports();
	writeFileSync(join(dataDir, 'cities.json'), JSON.stringify(cities));
	writeFileSync(join(dataDir, 'airports.json'), JSON.stringify(airports));
	rmSync(tmpDir, { recursive: true, force: true });

	console.log(`✓ public/data/cities.json   ${cities.length} cities`);
	console.log(`✓ public/data/airports.json ${airports.length} airports`);
}

main();
